-- Landing services CMS table for marketing/landing page
-- Run this script in your Supabase/Postgres instance before using the new UI.

BEGIN;

CREATE TABLE IF NOT EXISTS public.landing_services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icon TEXT NOT NULL, -- e.g. BookOpen, Users, Target, Clock, Brain
  title TEXT NOT NULL,
  description TEXT,
  features TEXT[] DEFAULT ARRAY[]::TEXT[],
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS landing_services_sort_idx
  ON public.landing_services (is_active, sort_order);

COMMENT ON TABLE public.landing_services IS
  'Services shown on the public landing page (1:1 tutoring, small group, test prep, etc.).';

COMMENT ON COLUMN public.landing_services.icon IS
  'Icon name used by the frontend (e.g. BookOpen, Users, Target, Clock, Brain).';

COMMENT ON COLUMN public.landing_services.features IS
  'Array of short bullet points/features for this service.';

-- Optional: seed with current marketing defaults
INSERT INTO public.landing_services (icon, title, description, features, sort_order)
VALUES
  (
    'BookOpen',
    '1:1 Tutoring',
    'Personalized sessions, 30 and 60 minutes. ESL support available for English language learners.',
    ARRAY[
      'Customized curriculum',
      'Real-time progress tracking',
      'Flexible scheduling',
      'ESL specialization'
    ]::TEXT[],
    1
  ),
  (
    'Users',
    'Small Group Sessions',
    'Collaborative learning for 5–10 students (2 credits or 1 hr class). Perfect for peer interaction.',
    ARRAY[
      'Collaborative learning',
      'Peer interaction',
      'Cost-effective',
      'Social learning environment'
    ]::TEXT[],
    2
  ),
  (
    'Target',
    'Test Prep',
    'SAT, ACT, local exams. Comprehensive preparation with proven strategies and practice materials.',
    ARRAY[
      'SAT & ACT prep',
      'Local exam support',
      'Practice tests',
      'Strategy sessions'
    ]::TEXT[],
    3
  ),
  (
    'Clock',
    'Homework Help & Study Skills',
    'Build lifelong learning habits. Support with daily assignments and developing effective study techniques.',
    ARRAY[
      'Daily homework support',
      'Study skill development',
      'Time management',
      'Academic planning'
    ]::TEXT[],
    4
  ),
  (
    'Brain',
    'Executive Function Coaching',
    'Time management, planning, focus. Essential skills for academic and personal success.',
    ARRAY[
      'Time management',
      'Organization skills',
      'Focus training',
      'Planning strategies'
    ]::TEXT[],
    5
  )
ON CONFLICT DO NOTHING;

COMMIT;


